### ISSUE TITLE
Add input argument to the UI binary

### ISSUE THREAD

**Issue by Bluscream** [ncs-sniper/SII_Decrypt#2]
It would be a neat little extra if even the UI binaries would accept one command line argument "%1" (the input file) that would make it possible to assign the UI exe to .sii files

**Comment by ncs-sniper** [comment]
Will do.

**Comment by Bluscream** [comment]
Thanks :)

**Comment by ncs-sniper** [comment]
Implemented in commit f0213a317874850ca7f2f04844504d6fa16e8c14

**Comment by ncs-sniper** [comment]
Changed my mind - I won't be doing release yet, there are too few changes for a new public version. I have at least recompiled so you can grab binaries from bin branch if you want.

**Comment by Bluscream** [comment]
Sure thing thanks :)
