### ISSUE TITLE
Lazarus DLLs have no exported functions

### ISSUE THREAD

**Issue by CaptainFlint** [ncs-sniper/SII_Decrypt#5]
In the latest commits, the DLLs built with Lazarus have no exports, thus they are impossible to use from other programs. The Delphi one looks OK, but there is no 64-bit version of it.

**Comment by ncs-sniper** [comment]
You are right.
The problem is that I have cleaned project files and along with it removed reference that was needed to build the export tables. Will correct asap.

**Comment by ncs-sniper** [comment]
It should be corrected in 1.4.2-rc1
