### ISSUE TITLE
Save cannot be decrypted (ST job inprogress)

### ISSUE THREAD

**Issue by CaptainFlint** [ncs-sniper/SII_Decrypt#6]
I have some save files which cannot be decoded, the error message is:
```
An error has occured. Error message:
  TSIIBin_Decoder.LoadLayoutBlockLocal: Unsupported value type (0x00000017).
```
These saves are made in ATS version 1.33.1.29 (open beta) while doing a Special Transport job. The saves from before taking the job and after the job was finished, are decoded without problems, so I think having that job active is the culprit.

I've attached a sample of the save made with `g_save_format 2`. The main `game.sii` cannot be decoded; the auxiliary file `game.sii.0` is also binary (which is strange, looks like SCS changed `g_save_format` behavior), but it can be decoded; and (just in case) I included the decoded text copy `game.sii.decoded`.
[test-save.zip](https://github.com/ncs-sniper/SII_Decrypt/files/2661149/test-save.zip)

**Comment by ncs-sniper** [comment]
Yeah, seems llike a new value type was introduced. I will look at the saves and do something about it.

**Comment by ncs-sniper** [comment]
It should be corrected in 1.5. Since I don't have textual reference for type 0x17, I had to guess how to convet it. Can you please try to decode the save using 1.5 and load it into the game, to see whether the current scheme works?

**Comment by CaptainFlint** [comment]
I'm not sure how to test it properly. I've loaded the decoded save, and the game did not crash and did not post any error messages in the log, and it spawned me in what looked like the correct position. Is this enough, or should I also look at some particular detail?

**Comment by ncs-sniper** [comment]
That should hopefully be enough. Many thanks for testing it!
